spring:
  datasource:
    url: jdbc:mysql://localhost:3308/msadb?userSSL=false&serverTimezone=UTC
    username: '{cipher}AQBaTLQiW7R2bidv1qAM//MzMu4N5oYA4tU0EKf8MoOreKOJ78hSlhO3VCnYRznpWkQbM6xhfX9O4njk/WhflehK7UQunlo1jyNNkhXrt0htc0quhbzotyQOiZWzRKEXDNxCMmNt9qqkSrJvC4zjN17MdvIeqr6t522GEljDs+InoaKONVdyogQkCjyV06tSiDflSYy/O2IZNkqijEIcM9MBEM+02CUbNqpJ5NtLPm+5AnIeevEapGFMKyPSkOtNshbX2+/SELHBvTvLGCT6mh5QY1M9sB5oU8Md2sd2EsbIpOOJ5/6fncZ5pmg7/a7XSDQtHnqdS+ElFSUZi6k4aTYi0Uz4mXplZOKqCfBmtukYjs8sMgw7OcQIjbzHzuZV2As='
    password: '{cipher}AQBaTLQiW7R2bidv1qAM//MzMu4N5oYA4tU0EKf8MoOreKOJ78hSlhO3VCnYRznpWkQbM6xhfX9O4njk/WhflehK7UQunlo1jyNNkhXrt0htc0quhbzotyQOiZWzRKEXDNxCMmNt9qqkSrJvC4zjN17MdvIeqr6t522GEljDs+InoaKONVdyogQkCjyV06tSiDflSYy/O2IZNkqijEIcM9MBEM+02CUbNqpJ5NtLPm+5AnIeevEapGFMKyPSkOtNshbX2+/SELHBvTvLGCT6mh5QY1M9sB5oU8Md2sd2EsbIpOOJ5/6fncZ5pmg7/a7XSDQtHnqdS+ElFSUZi6k4aTYi0Uz4mXplZOKqCfBmtukYjs8sMgw7OcQIjbzHzuZV2As='
    driver-class-name: com.mysql.cj.jdbc.Driver

token:
  expiration_time: 864000000
  secret: '{cipher}AQDAZUD4mlUcI6J0mFsjTK81zg12paICfmU5a/4gsIkatsb1oSm4Oyat9yM4haQDchOQF4/VGp842FLbJG/MhW2OMIwwDRCW/kbisPgXM3mM497LHkBfTLdiQrh+oG05OLBWtq5kRIFm8ImJ7gpGfcXOXL5MinhdY4rvDF2LjRO5PtuSOHl4FLBqsLN7Bwviq66aXt99rhlOJbwGuaerixd2tlvWPUKSpm3TD/N1nue6guXtcjWx6MefKSgxRZftMfz7w8y06Wm7QcZm3NY8VJAu5smzwitJ+T6XdgJa7GSWAxzRcTjD6N79CBlfUQOW73N/T3nymutEYLLGxwVRA4e2qWRaTn3vBNofuws31UGcvFcl6A7VfH2nXS4syoKF8NQ='

order_service:
  url: http://order-service/order-service/%s/orders